import { pgTable, text, timestamp, boolean, integer, real, jsonb } from "drizzle-orm/pg-core";

// Base outlets definition
export interface OutletConfig {
  id: string;
  name: string;
  language: string;
  region: string;
  ownershipType: "industrial_conglomerate" | "family_dynasty" | "digital_independent" | "state_public" | "regional_political";
  ownershipDetails: string;
  ownershipCitationUrl: string;
  feeds: string[];
  isActive: boolean;
}

export const OUTLETS_REGISTRY: OutletConfig[] = [
  // Phase 1 Active Outlets (8 outlets across English & Hindi)
  {
    id: "the-hindu",
    name: "The Hindu",
    language: "en",
    region: "National (Southern Origin)",
    ownershipType: "family_dynasty",
    ownershipDetails: "Published by Kasturi & Sons Ltd., owned by the Kasturi family.",
    ownershipCitationUrl: "https://india.mom-gmr.org/en/owners/companies/detail/company//kasturi-sons-ltd/",
    feeds: ["https://www.thehindu.com/news/national/feeder/default.rss"],
    isActive: true,
  },
  {
    id: "indian-express",
    name: "The Indian Express",
    language: "en",
    region: "National",
    ownershipType: "family_dynasty",
    ownershipDetails: "Published by Indian Express Group, controlled by the Vivek Goenka family.",
    ownershipCitationUrl: "https://india.mom-gmr.org/en/owners/companies/detail/company//the-indian-express-pvt-ltd/",
    feeds: ["https://indianexpress.com/section/india/feed/"],
    isActive: true,
  },
  {
    id: "ndtv",
    name: "NDTV",
    language: "en",
    region: "National",
    ownershipType: "industrial_conglomerate",
    ownershipDetails: "Majority 64.7% stake held by AMG Media Networks (Adani Group) acquired in 2022-2023.",
    ownershipCitationUrl: "https://india.mom-gmr.org/en/owners/companies/detail/company//amg-media-networks-limited/",
    feeds: ["https://feeds.feedburner.com/ndtvnews-india-news"],
    isActive: true,
  },
  {
    id: "the-wire",
    name: "The Wire",
    language: "en",
    region: "Digital Native / National",
    ownershipType: "digital_independent",
    ownershipDetails: "Published by Foundation for Independent Journalism (FIJ), a Section 8 not-for-profit company.",
    ownershipCitationUrl: "https://thewire.in/about-us",
    feeds: ["https://thewire.in/rss"],
    isActive: true,
  },
  {
    id: "dainik-jagran",
    name: "Dainik Jagran",
    language: "hi",
    region: "Northern Hindi Belt",
    ownershipType: "family_dynasty",
    ownershipDetails: "Published by Jagran Prakashan Ltd., controlled by the Gupta family.",
    ownershipCitationUrl: "https://india.mom-gmr.org/en/owners/companies/detail/company//jagran-prakashan-ltd/",
    feeds: ["https://www.jagran.com/rss/news-national.xml"],
    isActive: true,
  },
  {
    id: "amar-ujala",
    name: "Amar Ujala",
    language: "hi",
    region: "Northern Hindi Belt",
    ownershipType: "family_dynasty",
    ownershipDetails: "Published by Amar Ujala Publications Ltd., owned by the Maheshwari family.",
    ownershipCitationUrl: "https://india.mom-gmr.org/en/owners/companies/detail/company//amar-ujala-publications-ltd/",
    feeds: ["https://www.amarujala.com/rss/national-news.xml"],
    isActive: true,
  },
  {
    id: "bbc-hindi",
    name: "BBC News Hindi",
    language: "hi",
    region: "National / Vernacular",
    ownershipType: "state_public",
    ownershipDetails: "Operated by Collective Newsroom for BBC World Service, independent public broadcaster trust model.",
    ownershipCitationUrl: "https://www.bbc.com/hindi/institutional-50074213",
    feeds: ["https://feeds.bbci.co.uk/hindi/rss.xml"],
    isActive: true,
  },
  {
    id: "dinamalar",
    name: "Dinamalar",
    language: "ta",
    region: "Tamil Nadu",
    ownershipType: "family_dynasty",
    ownershipDetails: "Founded by T. V. Ramasubba Iyer, family-owned Tamil daily.",
    ownershipCitationUrl: "https://india.mom-gmr.org/en/owners/companies/detail/company//dinamalar-publications/",
    feeds: ["https://rss.dinamalar.com/national.asp"],
    isActive: true,
  },

  // Additional registered outlets
  {
    id: "times-of-india",
    name: "The Times of India",
    language: "en",
    region: "Metropolitan / National",
    ownershipType: "family_dynasty",
    ownershipDetails: "Owned by Bennett, Coleman & Co. Ltd. (BCCL) / Sahu Jain family.",
    ownershipCitationUrl: "https://india.mom-gmr.org/en/owners/companies/detail/company//bennett-coleman-co-ltd-bccl/",
    feeds: ["https://timesofindia.indiatimes.com/rssfeedstopstories.cms"],
    isActive: false,
  },
  {
    id: "hindustan-times",
    name: "Hindustan Times",
    language: "en",
    region: "National",
    ownershipType: "industrial_conglomerate",
    ownershipDetails: "Operated by HT Media Ltd, controlled by Shobhana Bhartia (KK Birla family).",
    ownershipCitationUrl: "https://india.mom-gmr.org/en/owners/companies/detail/company//ht-media-ltd/",
    feeds: ["https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml"],
    isActive: false,
  },
  {
    id: "scroll",
    name: "Scroll.in",
    language: "en",
    region: "Digital Native / Policy",
    ownershipType: "digital_independent",
    ownershipDetails: "Published by Scroll Media Inc., independent digital journalism portal.",
    ownershipCitationUrl: "https://scroll.in/about",
    feeds: ["https://scroll.in/feed"],
    isActive: false,
  },
  {
    id: "the-print",
    name: "ThePrint",
    language: "en",
    region: "Digital Native / National",
    ownershipType: "digital_independent",
    ownershipDetails: "Founded by Shekhar Gupta, Printline Media Pvt. Ltd.",
    ownershipCitationUrl: "https://theprint.in/about-us/",
    feeds: ["https://theprint.in/feed/"],
    isActive: false,
  },
  {
    id: "newslaundry",
    name: "Newslaundry",
    language: "en",
    region: "Digital Native / Media Watchdog",
    ownershipType: "digital_independent",
    ownershipDetails: "Subscriber-funded media criticism platform co-founded by Abhinandan Sekhri.",
    ownershipCitationUrl: "https://www.newslaundry.com/about",
    feeds: ["https://www.newslaundry.com/feed"],
    isActive: false,
  },
  {
    id: "deccan-herald",
    name: "Deccan Herald",
    language: "en",
    region: "Southern / Karnataka",
    ownershipType: "family_dynasty",
    ownershipDetails: "Published by The Printers (Mysore) Pvt. Ltd., owned by the Nettakallappa family.",
    ownershipCitationUrl: "https://india.mom-gmr.org/en/owners/companies/detail/company//the-printers-mysore-pvt-ltd/",
    feeds: ["https://www.deccanherald.com/rss/national.rss"],
    isActive: false,
  },
  {
    id: "navbharat-times",
    name: "Navbharat Times",
    language: "hi",
    region: "Northern Hindi Belt",
    ownershipType: "family_dynasty",
    ownershipDetails: "Hindi daily of BCCL (Times Group).",
    ownershipCitationUrl: "https://india.mom-gmr.org/en/owners/companies/detail/company//bennett-coleman-co-ltd-bccl/",
    feeds: ["https://navbharattimes.indiatimes.com/rssfeeds/2364.cms"],
    isActive: false,
  },
  {
    id: "anandabazar",
    name: "Anandabazar Patrika",
    language: "bn",
    region: "Eastern / West Bengal",
    ownershipType: "family_dynasty",
    ownershipDetails: "Published by ABP Pvt. Ltd., owned by the Sarkar family.",
    ownershipCitationUrl: "https://india.mom-gmr.org/en/owners/companies/detail/company//abp-pvt-ltd/",
    feeds: ["https://www.anandabazar.com/rss/national-news"],
    isActive: false,
  },
  {
    id: "daily-thanthi",
    name: "Daily Thanthi",
    language: "ta",
    region: "Tamil Nadu",
    ownershipType: "family_dynasty",
    ownershipDetails: "Founded by S. P. Adithanar, prominent mass-circulation Tamil daily.",
    ownershipCitationUrl: "https://india.mom-gmr.org/en/owners/companies/detail/company//daily-thanthi-group/",
    feeds: ["https://www.dailythanthi.com/rss/news/india"],
    isActive: false,
  },
  {
    id: "eenadu",
    name: "Eenadu",
    language: "te",
    region: "Andhra Pradesh / Telangana",
    ownershipType: "family_dynasty",
    ownershipDetails: "Founded by the late Ramoji Rao, Ushodaya Enterprises / Ramoji Group.",
    ownershipCitationUrl: "https://india.mom-gmr.org/en/owners/companies/detail/company//ushodaya-enterprises-pvt-ltd/",
    feeds: ["https://www.eenadu.net/rss/national.xml"],
    isActive: false,
  },
  {
    id: "loksatta",
    name: "Loksatta",
    language: "mr",
    region: "Western / Maharashtra",
    ownershipType: "family_dynasty",
    ownershipDetails: "Marathi broadsheet daily published by The Indian Express Group.",
    ownershipCitationUrl: "https://india.mom-gmr.org/en/owners/companies/detail/company//the-indian-express-pvt-ltd/",
    feeds: ["https://www.loksatta.com/feed/"],
    isActive: false,
  },
  {
    id: "mathrubhumi",
    name: "Mathrubhumi",
    language: "ml",
    region: "Southern / Kerala",
    ownershipType: "family_dynasty",
    ownershipDetails: "Published by The Mathrubhumi Printing and Publishing Co. Ltd.",
    ownershipCitationUrl: "https://india.mom-gmr.org/en/owners/companies/detail/company//the-mathrubhumi-printing-and-publishing-co-ltd/",
    feeds: ["https://www.mathrubhumi.com/rss/news/india"],
    isActive: false,
  },
];
